project:
  type: website

website:
  title: "Shreya Mukhopadhyay"
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: CV
        href: ./assets/shreya-cv.pdf
        target: blank
    right:
      - icon: envelope-at-fill
        href : mailto:mshreyacr7@gmail.com
      - icon: linkedin
        target: blank
        href: https://www.linkedin.com/in/shreya-mukhopadhyay-078344203/
      - icon: facebook
        target: blank
        href: https://www.facebook.com/anushka.gupta.7315720?mibextid=ZbWKwL
format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full


