---
title: "Role of Virome Against Enteropathogens Present in ganges Water"
author: "Shreya Mukhopadhyay"
date: "2021-07-20"
categories: [Virology, Pathology]
abstract: >
    The Ganges is home to a high variety of microorganisms, both beneficial and harmful. Anthropogenic activities, including pollution from industrial effluents and waste from religious rituals, cause depletion in microbial communities at urban sites of river Ganga. The Ganga water is frequently used for drinking, cooking, and bathing purposes due to the ancient belief that Ganges water does not putrefy, even after long periods of storage. About 200 years ago, British colonial scientists suggested that Ganga may contain unique microbial life, which makes it relatively more resilient to putrefaction. That unique microbial life is the virome. The presence of various kinds of viruses gives Ganga its self-purificatory property. 
---

# Introduction
Water is the most fundamental resource required to sustain life. Water of river Ganga has been used from time immemorial for remedial purposes. The Ganga water is frequently used for domestic purposes. It is well known that the Ganga water has become inadequate and unsafe for drinking over the years. So, the threat of waterborne diseases including diarrhoea and severe gastro-enteritis with consequent morbidity and mortality haunts the nation. The Ganga River is a home to a large population of pathogenic bacterial species which have developed multiple anti-microbial resistance strategies over the years. But still the river water continues to be used for domestic purposes and, surprisingly, the effects are not as deadly as expected. The reason behind this peculiarity is expected to be the presence of virome in the river Ganga. The virome present in the river and in the human gut functions as a purificatory agent safe-guarding the Ganga water users from the deadly effects of its pathogenic bacterial population. This blog revolves around the interaction of virome present in the Ganges with the pathogenic bacteriome and with the river water consumers. It aims at highlighting the mechanisms involved in the protective roles played by virome against severe waterborne diseases. This blog further aims to present certain findings which suggest that Ganga water has certain novel antimicrobial attributes, besides its remarkable fluidity, which may provide a much-needed basis for the development of new antimicrobial compounds in the near future. 

# Outreaches of Ganga 
Ganges River is the great river of the plains of the northern Indian subcontinent. Despite its importance, its length of 1,560 miles (2,510 km) is relatively short compared with the other great rivers of Asia or of the world. Rising in the Himalayas and emptying into the Bay of Bengal, it drains one-fourth of the territory of India, and its basin supports hundreds of millions of people. 

The Ganga River originates from the confluence of the Bhagirathi and Alaknanda at Devaprayag town of Uttarakhand. The Alaknanda River emerges from the foot of Gangotri Glacier at Gomukh in the western Himalayas. After flowing through its narrow Himalayan valley, a dam at Haridwar diverts its path towards Uttar Pradesh. The river, whose course has been roughly southwest until this point, now begins to flow southeast through the plains of northern India. Then, the river flows through Bihar and West Bengal and enters Bangladesh and finally drains into the Sunderbans delta in the Bay of Bengal. 

# The Present Condition of the River Ganga 
The origin, growth and protection of life of all forms need a driving force, which is provided by water. Ganga is the largest river of India and many livelihoods depend extensively on the Ganges for their water needs. However, the river basin is facing an ever-increasing population, exponential growth in tanneries, and urbanization, leading to high atmospheric deposition and organic carbon buildup in the river basin. On 16th May 2018, a local news published that, thousands of fishes were found dead in the Ganges at Kannauj, Uttar Pradesh, India, and a team of experts from the National Wildlife Institute of India, Dehradun, and the UP-Pollution Control Board (UPPCB) investigated this matter and revealed that illegal and intermittent discharge of toxic materials including plastic dumping to the river caused the mass killing of fishes. 
The DO level depleted substantially due to tannery effluents, increased BOD values (≥5.2ppm) 2012–2016 due to the direct flow of sewage drains in the river and establishment of the large number of apartments, industries, and hospitals on the bank of river Ganga made the river water unfit for drinking and even for bathing purposes; however, river water remained highly contaminated even after the treatment of sewage and tannery effluents. This calls for immediate checks on the recreational activities and mass bathing rituals in the Ganges. 
Higher coliform contamination (5–20 times higher than the permissible limit) in the Ganges is due to the direct discharge of sewage into the river and prevalent open defecation around the bank of the river. 
Cultivable Vibrios Count was found to be considerably higher through-out the year, which results in annual periodic diarrheal recurrences in monsoon and post monsoon seasons in South Bengal. Rapid urbanization and industrialization along the river banks of Ganga River exert potential threat to public health by causing microbial and chemical contamination. 

# Ganga Vs Other Indian Rivers 
A study established that the river Ganga is the most pristine of all the Indian rivers. Although the presence of pathogens, heavy metals and other toxicities are higher in Ganga as compared to other rivers, still Ganga retains its purity due to the fact that it contains a higher number of bacteriophages as compared to Yamuna and Narmada. 

# Major Causes of Pollution in Ganga 
The large amount of untreated waste disposal in the Indian rivers is due to the lack of functional treatment plants, 6.7% towns and cities have partial sewage treatment while only 0.25% has full sewage treatment. Of which, most are primarily useless due to their lack of functionality by construction and upkeep, lack of workforce coupled with minimal management and lack of constant electricity. Also, faeces in open fields easily make its way into streams and runoffs, thus contaminating nutrition sources. Almost 1 billion Liters of untreated sewage are dumped in the river daily which has doubled in the last 20 years and another 100% increase in the following 20 years is predicted. 

# Self-Purificatory Aspects of Ganga 
So far, this blog has discussed about the level of contamination in the Ganges, the major causes of pollution in the river and how these factors contribute in making the Ganga a severe threat to our health. High amounts of Enteropathogens are deposited in Ganges having high potential to cause fatal health issues in children and adults residing in the banks of the Ganges, children being at higher risk than adults. So, a very high rate of disease occurrence and infectivity is expected to result from the consumption of Ganga water. 

However, the reality is otherwise. In the past it has been established that the Ganges possesses a high self-purifying capacity. The auto-purifying ability of the river Ganga is derived from its surprisingly high capacity to maintain dissolved oxygen (an imperative limnological factor representing level of water eminence and organic pollutants in the water body) inherited from this environment. Lack of adequate DO leads to infected condition and increases BOD in the river. The maintenance of high DO levels is performed by specific bacteriophages which feed on certain bacterial population of the river, thus lowering its pathogenic load. 

# The Call for the Use of Virome against Enteropathogens of Ganges 
Now the question arises that why virome is thought to be responsible for the self-purificatory aspects and the pristine nature of Ganges. Several studies have shown that the Ganges exhibit much higher levels of Bacteriophages than any other river of the country. The presence of bacteriophages at such high level correlates with the self-purificatory properties of Ganga. Bacteriophages being able to lyse the bacterial cells and affect their population seem to have a very significant role in lowering the level of contaminants in the Ganges as well as bringing down the risk of serious health hazards. 

E. coli is a preferred indicator for freshwater recreation and its presence provides direct evidence of faecal contamination from warm-blooded animals. The anti-microbial agent resistant profile reflected that river Ganga is a reservoir of multiple-antimicrobial-resistant E. coli, most prevalent pathotypes being enterohemorrhagic or shiga toxin producing E. coli (EHEC or STEC) and enterotoxigenic E. coli (ETEC). E. coli isolates from urban areas/point sources have resistance to more antibiotics than rural/nonpoint source isolates possibly due to greater exposure to antibiotics. E. coli may transit between virulent and nonvirulent forms by acquiring or losing virulence genes encoded by plasmid(s) making these forms indistinguishable from normal gut flora in individuals consuming river water for daily needs. This may further indicate that the presence of E. coli exhibiting plasmid encoded virulence genes in the Ganga water may lead to emergence of new pathogenic variants. 

A study on Multi Drug Resistant Bacteria in the Ganga surface waters of Kolkata detected all common antibiotics resistant bacteria in all water resources, especially ampicillin or amoxicillin. Superbugs were detected as resistant to multiple drugs, also to imipenem, linezolid, colistin, lomofloxacin and amikacin. More than 2000 tons antibiotics are made these days and MDR bacteria were maximum at the industry sites and its adjacent river. In Escherichia coli and Pseudomonas aeruginosa many drug efflux genes are assembled which in much way resemble to ABC transporter genes actively involved in bio-molecules transport across the cell membrane. 
The incorruptible nature of the water in fresh, 8-year-old, and 16-year-old Ganga water samples spiked with E. coli O157:H7 showed that Eight-year-old water had a better ability to kill E. coli O157:H7 compared with boiled water and water passed through a 0.2-lm-poresize membrane filter. 

The microbial community structure could be a good indicator for revealing the severity of heavy metal contamination. The middle and lower stretches of Ganga have been reported to have high microbial and heavy metal contamination. Further, some bacterial species which are present in Ganga water, e.g. Bacillus cereus, B. thuringiensis and B. subtilis, are known to reduce hexavalent chromium (CrVI), a toxic and carcinogenic form, to the non-toxic trivalent chromium (CrIII) which further indicate the curative properties of Ganga water because CrIII is an essential nutrient that promotes metabolism of glucose, fat and protein by facilitating the action of insulin in humans and animals. Ganga exhibits certain distinct qualities in terms of higher alkalinity and pH and abundance of trace elements which have a role in self-purificatory and incorruptible properties of river Ganga by promoting growth of bacteriophages. Phages require divalent metal ions, such as Ca, Mg, Zn, Fe and Co, for their growth as some phages require metal ions for stability, and others require for attaching to the host cell for the entry into the nucleic acid and for multiplication.
 
All these evidences call for study about the implications of virome. Virome seems to have strong contribution in the curative properties of Ganga water.

# Why to Rely on Virome? 

Several types of purifying activities have been adopted to have a pathogen-free Ganga, but none have been proved to be effective enough. However, a natural purification mechanism has been observed in the Ganges in several studies time and again. Evidences of antimicrobial activities shown by viral population against the deadly pathogenic strains of various bacterial species as well as resuming the purifying ability of water by the virtue of the presence of viruses in the water samples have been recorded in many studies. Some of which are listed below.  

- In 1896, Ernest Hankin found phages that thrived in tap water died in non-boiled but filtered Ganges water and also died in boiled Ganges water.
- In 1916, Felix d’Herelle identified factors which are heat labile and difficult to filter but exhibit antimicrobial activity.
- IIT Roorkee in 2019, isolated Superphage from Ganga, decoded lysine gene and cloned lysine protein with great potential as antibacterial pharmaceutical.
- The Ganga water is believed to exhibit antibacterial properties and exhibit high DO even in extremely polluted conditions by virtue of the presence of Virome.
- CSIR identified >20 types of phages in Ganges that fight microbes which cause TB, pneumonia, cholera etc.

# Nature and Components of the Human Gut Virome 
A numerically prevalent and persisting fraction of the viral community is present in the human gut, termed as the persistent personal virome (PPV) which consists mainly of virulent bacteriophages predicted to target major taxonomic groups of gut bacteria. The human gut virome is highly individual specific and stable for up to 1 year. A stable and predominant fraction of viruses constitutes a persistent personal virome which can be linked to highly predominant gut bacterial taxa. Virulent crAss-like and Microviridae bacteriophages predominate and persist in the gut. 

## Effect of Gut Virome in Homeostasis and Dysbiosis 
The mammalian intestinal virome comprises viruses that infect eukaryotic and prokaryotic cells. It is established soon after birth and is dominated by bacteriophages. Composition of the virome is influenced by numerous factors that affect viruses directly (infection) or change host-cell populations (e.g., antibiotics, diet). The virome establishes a mutualistic relationship with eukaryotes/prokaryotes, contributing to intestinal homeostasis by influencing microbial ecology and host immunity. Homeostasis is maintained by the presence of diverse microbiota in the gut, intact intestinal barrier (epithelial cells and mucin), proper bacteriophage adherence to mucus and controlled activation of immune system. Members of the virome may contribute to the pathogenesis of certain diseases via microbial host lysis leading to dysbiosis (a microbial imbalance or any changes to the composition of resident microbial communities relative to the community found in healthy individuals), infection of epithelial cells, and/or translocation of the compromised or damaged mucosal barrier to gain access to underlying tissues and immune cells, leading to immune activation. Establishment of homeostasis or dysbiosis depends on diet, nutritional status, age, lifestyle, medication, immune status and environment. 

Many bacterial species inhabiting our Gastro-Intestinal track are beneficial for us which maintain a quite stable population in the human gut. These constitute the normal microbiota of our gut. However, this normal microflora gets imbalanced under certain cases, like during the course of antibiotics. This imbalance is prevented by the human gut virome. Viruses provide antibiotic resistance via Horizontal Gene Transfer (HGT). HGT also leads to the occurrence of virulence in the bacterial species which triggers immune response in the host. Activated immune system generates Reactive Oxygen Species, which in turn triggers more HGT. Antibiotics also cause induction of prophage and lysis of commensals. As a result of which pathogenic bacterial species invade the host tissues due to elimination of competition. So, a supplement for use of antibiotic is necessary, which is provided by Phage Therapy. 

Phage Therapy can be administered to kill pathogens. Latent viral infection causes immune activation and prevents pathogenic infection and removal of pathogens. Thus, a Phage-Mediated Immunity is generated. 

The gut microbiota has a dual role when it interacts with viruses. Microbiota–virome interactions in mucosal surfaces are of the following two types: 

- Microbiota can have a protective role against viral infections. E.g. bacteria from the Lactobacillus genus inhibit Norovirus infection, bacterial flagellin activates TLR5 to produce inflammatory cytokines (IL-22, IL-18), B. breve stimulates the production of pro-inflammatory cytokines (IFN-g, IL-4, TNFa) against viruses. The gut microbiota regulates the production of ROS and defensins, and the activation of Th1 and CTL against viral infections. 
- Microbiota can function as an evasion mechanism, where viruses can bind to bacterial structural molecules (such as LPS) or bacterial pili or membranes to induce immunotolerance through the increase of anti-inflammatory cytokines (IL-10) and to infect host cells. 

Thus, interactions of viruses with the host immune system as well as the commensal bacteriome of the host are both positively and negatively regulated. More studies will reveal the proper mechanisms of these interactions and how these interactions can be directed for the advent of human utility. 

Highly diverse viral communities inhabit the human body, including eukaryotic viruses and a high abundance of bacteriophages. Both virus types are important to the balance between health and disease, not only because they infect human cells but also because they positively and negatively modulate the human microbiome. Viruses access the human body through food and through contact with plants, animals, and other humans. Environmental factors and internal factors (such as immunity and genetics) greatly influence the composition and dynamics of the human virome. 

Their physiological role in humans is yet to be defined. One hypothesis proposes that some of them promote human health indirectly, by eliminating viral pathogens through cross-immunity, and/or directly, by viral interference. A study has shown that latent infection with murine gammaherpesvirus 68 (a model for EBV) or murine CMV (a model for human CMV) confers protection against Listeria monocytogenes and Yersinia pestis in mice. It has also been shown that in individuals with HIV, coinfection with the hepatitis G virus (GB virus type C) delays progression to AIDS. However, some viruses may increase the risk of secondary infection with a similar but more virulent genotype or other microbial/viral agents by maintaining chronic inflammation, and/or promote viral carcinogenesis in individuals with a specific immunologic disorder. Several members of the Papillomaviridae, Herpesviridae and Polyomaviridae families have been linked to human cancers. 

So, it can be said that viral interactions with humans go beyond simple parasitism and that several eukaryotic viruses have established persistent interactions with their host. The adverse or beneficial effects of these interactions probably depend on the anatomical site of infection, the host genotype/immune status, and the presence of other viruses and microbes.

# Methods of detection of Virus or VLPs from the Ganges 

Now that such a huge level of viral utility is estimated to be already occurring naturally in the Ganges as well as in our gut, it becomes highly necessary to have proper techniques to detect, isolate and identify Viruses or VLPs from the river water sample so that using them we can take a step towards making Ganga pathogen-free. This will help in making the use of Ganga water for various purposes safer. 

Various methods are already in use which detects viral samples from water samples. Some of which are PCR (RT PCR, qPCR), flow cytometry, MPN studies, plaque assays, observation of cytopathogenic effects, metagenome-based pathogen surveillance etc. The already in use methods need to practiced more efficiently and many more methods need to be introduced for studying the vast array of virus-mediated Ganges purification. 

# Conclusion 
It has been established and widely accepted that Ganga has self-purificatory activities owing to the presence of certain viral strains in it. The high abundance of virome in Ganges as compared to other rivers sheds light on this belief. Certain viruses are capable of digesting pollutants and contaminants including heavy metals and dangerous pathogens. Due to the presence of these kinds of viruses along with deadly pathogens and high order pollutants in Ganges, use of the river water is not life threatening. Although much more evidences are required for proper implementation of virome-mediated purification projects on the river. It is necessary to identify those viral species which are directly or indirectly involved in cleansing actions of the Ganges and use them for cleaning the river, making it pathogen-free and thus safer for domestic, agricultural as well as industrial use. 

# References

1.	Bhatnagar, M. K., Singh, R., Gupta, S., & Bhatnagar, P. (2013), Study of tannery effluents and its effects on sediments of river Ganga in special reference to heavy metals at Jajmau Kanpur, India. Journal of Environmental Research and Development, 8 (1), 56–59. 
2.	Ayesha Mariya & Chitranjan Kumar & Mohd. Masood & Niraj Kumar (2019), The pristine nature of river Ganges: its qualitative deterioration and suggestive restoration strategies, DOI: 10.1007/s10661-019-7625-7 
3.	CPCB. (2018). ENVIS Centre on Control of Pollution Water Air and Noise. Central Pollution Control Board, Ministry of Environment and Forests, Government of India: http://www.cpcbenvis.nic.in/water_quality_data.html#. Accessed 8 June 2020. 
4.	Sushil Kumar Singh, Manish Kumar Kanth, Dhirendra Kumar, Rishikesh Raj, Abhijeet Kashyap, Pranav Kumar Jha, Ashutosh Anand, Kumari Puja, Suman Kumari, Yusuf Ali, Ram Shiv Lokesh, Shivam Kumar (2017) Analysis of Water Quality of River Ganga from Digha Ghat to Gai Ghat in Patna District, Bihar, India, DOI: 10.21276/ijlssr.2017.3.5.14 
5.	Kumari Satya and Chandravir Narayan (2018), Study of Physico-chemical and Biological Characteristics of the Water of River Ganga at Patna, India, DOI: 10.12944/CWE.13.3.10 
6.	Suvajit Saha, Madhumanti Halder, Subham Mookerjee, Anup Palit (2019), Seasonal influence, enteropathogenic microbial load and diarrheal enigma in the Gangetic Delta, India: Present scenario and health implications, DOI: 10.1016/j.jiph.2019.01.066 
7.	https://en.wikipedia.org/wiki/Water_pollution_in_India, Accessed on 11th August 2020 
8.	http://www.cseindia.org/userfiles/aagd2013_report.pdf, Accessed on 11th August 2020 
9.	http://www.bbc.com/news/health-33980904, Accessed on 11th August 2020 
10.	Das S. Cleaning of the Ganga. Journal Geological Society of India. 2011;78:124-130 
11.	Wetzel R.G., Likens G.E. Limnological analysis, 3rd ed. Springer-Verlag, New York, 391. 2006. 
12.	Water Contamination: A Growing Epidemic https://microbewiki.kenyon.edu/index.php/Water_Contamination:_A_Growing_Epidemic Accessed on 12th August 2020 
13.	Siya Ram, Poornima Vajpayee and Rishi Shanker (2007), Prevalence of Multi-Antimicrobial-Agent Resistant, Shiga Toxin and Enterotoxin Producing Escherichia coli in Surface Waters of River Ganga, DOI: 10.1021/es0712266 
14.	Hacker, J.; Blum-Oehler, G.; Mu¨hldorfer, I.; Tscha¨pe, H. (1997), Pathogenicity islands of virulent bacteria: structure, function and impact on microbiological evolution. Mol. Microbiol. 23, 1089-1097. 
15.	Asit Kumar Chakraborty, Kousik Poira, Debashray Saha, C. Halder, S. Das and S. Nandi (2018), Multidrug-Resistant Bacteria with Activated and Diversified MDR Genes in Kolkata Water: Ganga Action Plan and Heterogeneous Phyto-Antibiotics Tackling Superbug Spread in India, DOI: 10.13140/RG.2.2.17947.52001 
16.	McArthur AG, Waglechner N, Nizam F, Bhullara K, et al. (2013) The comprehensive antibiotic resistance database. Antimicrob Agents Chemther 57: 3348-3357. 
17.	Chandra Shekhar Nautiyal (2008), Self-Purificatory Ganga Water Facilitates Death of Pathogenic Escherichia coli O157:H7, DOI: 10.1007/s00284-008-9260-3 
18.	Zhang, Y., Li, H., Gong, L., Dong, G., Shen, L., Wang, Y., et al. (2017). Nano-sized Fe2O3/Fe3O4 facilitates anaerobic transformation of hexavalent chromium in soil–water systems. Journal of Environmental Sciences, 57, 329–337. 
19.	Dwivedi, S., Mishra, S., & Tripathi, R. D. (2018). Ganga water pollution: a potential health threat to inhabitants of Ganga basin. Environment International, 117, 327–338. 
20.	Upadhyay, N., Vishwakarma, K., Singh, J., Mishra, M., Kumar, V., Rani, R., & Sharma, S. (2017). Tolerance and reduction of chromium (VI) by Bacillus sp. MNU16 isolated from contaminated coal mining soil. Frontiers in Plant Science, 8, 778. 
21.	Sanjay Dwivedi & Puneet Singh Chauhan & Seema Mishra & Amit Kumar & Pradyumna Kumar Singh & Mohan Kamthan & Reshu Chauhan & Surabhi Awasthi & Sumit Yadav & Aradhana Mishra & Shekhar Mallick & Sanjeev Kumar Ojha & Sri Krishna Tewari & Rudra Deo Tripathi & Chandra Shekhar Nautiyal (2020). Self-cleansing properties of Ganga during mass ritualistic bathing on Maha-Kumbh. DOI: 10.1007/s10661-020-8152-2 
22.	Rakhuba, D. V., Kolomiets, E. I., Dey, E. S., & Novik, G. I. (2010). Bacteriophage receptors, mechanisms of phage adsorption and penetration into host cell. Polish Journal of Microbiology, 59, 145–155. 
23.	https://iasgatewayy.com/ganga-has-higher-proportion-of-antibacterial-agents/ 
24.	https://iasgatewayy.com/ganga-has-higher-proportion-of-antibacterial-agents/ 
25.	https://www.thehindu.com/news/national/ganga-has-higher-proportion-of-antibacterial-agents-study/article26890979.ece 
26.	https://timesofindia.indiatimes.com/city/chandigarh/Polluted-Ganga-has-healing-touch-thanks-to-viruses/articleshow/54504431.cms 
27.	Nicol´as Rascovan, Raja Duraisamy, and Christelle Desnues (2016) Metagenomics and the Human Virome in Asymptomatic Individuals. DOI: 10.1146/annurev-micro-102215-095431 
28.	Andrey N. Shkoporov, Adam G. Clooney, Thomas D.S. Sutton, Vimalkumar Velayudhan, R. Paul Ross, Colin Hill (2019). The Human Gut Virome Is Highly Diverse, Stable, and Individual Specific. DOI: https://doi.org/10.1016/j.chom.2019.09.009 
29.	S. R. Carding, N. Davis, L. Hoyles (2017). The Human Intestinal Virome in Health and Disease. DOI: 10.1111/apt.14280 
30.	Aislinn D. Rowan-Nash, Benjamin J. Korry, Eleftherios Mylonakis, Peter Belenky (2019). Cross-Domain and Viral Interactions in the Microbiome. DOI: 10.1128/MMBR.00044-18 
31.	Carolina Domínguez-Díaz, Alejandra García-Orozco, Annie Riera-Leal1, Jorge Ricardo Padilla-Arellano and Mary Fafutis-Morris (2019). Microbiota and Its Role on Viral Evasion: Is It with Us or Against Us? DOI: 10.3389/fcimb.2019.00256 
32.	Barton ES, White DW, Cathelyn JS, Brett-McClellan KA, Engle M, et al. (2007). Herpesvirus latency confers symbiotic protection from bacterial infection. Nature 447:326–29 
33.	Bhattarai N, Stapleton JT. (2012). GB virus C: The good boy virus? Trends Microbiol. 20:124–30 
34.	McLaughlin-DrubinME, Munger K. (2008). Viruses associated with human cancer. Biochim. Biophys. Acta 1782:127–50 
35.	Nicol´as Rascovan, Raja Duraisamy, and Christelle Desnues (2016). Metagenomics and the Human Virome in Asymptomatic Individuals. DOI: 1 0.1146/annurev-micro-102215-095431 
