---
title: "Gene Scissors Crispr-Cas9: How it Works, Therapeutic Applications and Associated Controversies"
author: "Shreya Mukhopadhyay"
date: "2021-01-24"
categories: [Genome editing, ]
---
This article was submitted to "Critical Essay Writing" competition held during January 23-January 25, 2021 by Prof. J.J. Ghosh Foundation. 

# Introduction
CRISPR-Cas9 technology is a new area of biomedical science that enables gene editing and it is helping in deciphering the genetic basis of many diseases like autism, cancer, sickle cell anaemia etc. This technology has been derived from the adaptive immune system of bacteria. In the year 2020, Emmanuel Charpentine and Jennifer A. Doudna shared the Nobel Prize in Chemistry for elucidating the molecular mechanism of the bacterial adaptive immune system, the CRISPR-Cas9 and repurposing it as a genetic engineering tool. New technologies often emerge and come from unexpected directions by people who are not necessarily trying to discover new technology, rather working on fundamental questions and come across a mechanism that reveals it to be something that can be harnessed for a very different purpose. 

The CRISPR field is very young. It all started when a few groups of scientists observed that a lot of bacteria have repetitive DNA sequence in their genomes that came to be called as CRISPR (Clusters of Regularly Interspaced Short Palindrome Repeats). They found that many bacteria have a distinctive feature in their chromosome that includes repetitive sequences flanking or bordering a unique sequence. In 2005, Bolotin et al, Mojica et al and Pourcel et al noticed that in many cases these unique sequences present in the CRISPR arrays that come from DNA found in bacteriophages. This was the first indication that these CRISPR arrays constitute an acquired immune system in bacteria. They also noticed that along with these CRISPR arrays were cas (CRISPR-associated) genes located near the CRISPR arrays in the bacterial chromosome which encodes for Cas proteins that are also a part of adaptive immunity used by bacteria to protect themselves from the virus present in the wild type environment.

# CRISPR-Cas9 in bacterial immune system
When viruses enter a bacterial cell, it injects its DNA into the bacteria and if the bacteria have a CRISPR array in the genome, it acquires new pieces of DNA from the virus and integrate them into the arrays keeping this pattern of repeats. The bacterial cell then makes a copy of that sequence in the form of an RNA molecule that is subsequently broken into smaller units each including one of the sequences derived from the virus along with the sequence coming from the repeats. Those RNAs are marked as CRISPR molecules by the presence of these repeats and they combine with a second RNA called tracrRNA (tracer RNA) to form a structure that binds to the protein called Cas9. This RNA-protein complex surveys the cell looking for the DNA sequence that has a match with the RNA sequence. If a match is found, then the protein-RNA complex unwinds the DNA locally forming an RNA-DNA hybrid. This is then followed by a Cas9 induced double strand break (DSB) in the foreign DNA. 

The CRISPR locus in bacteria constitutes of short repeat sequences arranged in palindromic fashion separated by spacers which bears unique sequences acquired from previous encounters with bacteriophages. An adenine and thymine rich leader sequence is located at the upstream of CRISPR loci which contains promoter and signal for the transcription of crRNA and successful integration of foreign genetic material into CRISPR array. Upstream of the leader sequence are the cas genes. crRNA and Cas protein form CRISPR-Cas complex mediates the silencing and cleavage of foreign nucleic acids. 

The CRISPR-Cas gene scissor program in bacteria involves a sequence of events. Firstly, the Spacer Acquisition step occurs in which the foreign DNA is captured and inserted into a spacer locus. The new spacers are usually added next to the leader sequence creating a chronological record of viral infections. The regions of phage genomes that are excised as spacers are called Protospacers. The next step is Biogenesis in which the crRNA formation occurs. The crRNA is initially transcribed as a single long transcript of the entire CRISPR array followed by cleavage by Cas protein to form crRNA. The crRNA has short palindromic repeat sequences which enable the RNA molecules to fold back and form hairpin structures that are recognized by some Cas proteins that further cleave and process these RNAs producing short crRNAs each containing one of the sequences acquired from viruses. 

So, the cells very effectively label these RNAs as crRNA by using unique sequence and structure tags. These crRNA associates with Cas proteins forming crRNA-Cas complex which ultimately recognize foreign nucleotides. The final step is the Interruption step in which a multifunctional Cas9 protein cleaves foreign DNA using its dual HNH domain and RuvC/RNase H-like endonuclease domains. Cas9 requires both the crRNA and tracrRNA for efficiently recognizing the foreign sequence and perform its cleavage activity. Cas9 is an amazing enzyme which can recognize dsDNA at positions in the DNA sequence that match a 20-nucleotide sequence in the gRNA (guide RNA). The gRNA has desired sequence and it tracks Cas9 to a particular site in the genome and triggers cleavage of the foreign DNA to make blunt Double Strand Breaks. 

In bacterial cells, these Double Strand Breaks in DNA are subjected to degradation. But if this system is introduced in a eukaryotic cell, the Double Strand Breaks are sophisticatedly repaired by introducing a small change at the site of the break as in Non-Homologous End Joining (NHEJ) or by introducing a new piece of DNA during the process of repair as in Homology Directed Repair (HDR). Thus, introducing Double Strand Breaks in a targeted fashion into the genomes of eukaryotic cells is a very effective way to conduct genome engineering. 

The CRISPR-Cas system can be broadly divided into classes on the basis of the number and types of Cas protein involved in these systems, called Class 1 and Class 2. Class 1 system includes multiple cas genes. Class 2, in contrast, typically includes one large protein that combines with crRNA to provide the protection to the cell.

# Repurposing CRISPR-Cas mechanism
## Implications CRISPR-Cas9 in cancer treatment
The first revolutionary idea for the repurposing of bacterial CRISPR-Cas immunity in genome editing and transcription control was given by Jinek et al in their hypothesis that tracrRNA:crRNA of Cas9 could be fused into a single chimeric RNA forming the sgRNA (single guide RNA) or simply gRNA (guide RNA) which contains a scaffold sequence to bind Cas9 and a targeting sequence to direct the system towards the target locus, a technique that would allow programmed DNA cleavage through engineering of chimeric RNA molecule. 

This powerful and versatile CRISPR-Cas editing tool has acquired immense attention among the oncology researchers. The powerful attribute of regulation of CRISPR-Cas9 on endogenous gene expression shows possible usage in cancer treatment. In several cancers like Ewing Sarcoma, Acute Myeloblastic Leukaemia and tumours like Glioblastoma Multiforme, the cancer progression involves predominant role of epigenetic factors. So, the cancerous growth can be deregulated by targeting the epigenetic machinery and its regulatory components. This can be performed by binding Cas9 protein either to histone modifier or other DNA methylation regulatory protein for epigenome editing. Tumour proliferation and invasion can be eliminated by employing CRISPR-Cas9 tools to target the tumour makers in cancer cells directly. A well-known example of CRISPR-Cas9 technology in drug discovery process in oncology is in ovarian cancer mouse model ID8, in which BRCA2 and TP53 genes were knocked-out in CRISPR-Cas mediated manner increasing their sensitivity to Poly-ADP-Ribose Polymerase (PARP) inhibitor, the rucaparib. This technology provides many advantages over other traditional methods including easy prediction of off-target sites, precise targeting of multiple genome sites simultaneously, easy design of genomic targets and targeting epigenetic changes occurring during carcinogenesis.

## Applications in CRISPR-Cas9 Stem Cell Research
An epic application of CRISPR-Cas9 technology in biomedical research is by combining this new genome editing tool with the potential of human pluripotent stem cells (hPSCs). hPSCs can be either generated from hESCs, human embryonic stem cells, arising directly from embryos or from iPSCs, induced pluripotent stem cells, generated from fibroblasts or other somatic cells by transfection of ‘reprogramming genes. The hPSCs is an important tool in regenerative medicine due to its excellent ability to self-renew indefinitely and differentiate into different types of somatic cells. This tool in collaboration with CRISPR-Cas9 technology can be used to introduce mutations in cell lines to generate disease models for study and research purposes and correct genetic defects to rescue pathological conditions.

## Haemoglobin deficiency reversal using CRISPR-Cas9
The CRISPR-Cas9 gene editing technology has been used to cure patients suffering from β-thalassemia and sickle cell disease. This technology has been used to modify DNA of stem cells. The BCL11 gene which is responsible for suppressing foetal haemoglobin production was deleted from the DNA of the stem cells. This allowed the stem cells to produce foetal haemoglobin so that the patients with congenital haemoglobin defects like β-thalassemia and sickle cell disease start to make enough foetal haemoglobin which will overcome the effect of defective haemoglobin. The first two patients who have received this treatment have showed successful results and are under continuous monitoring.

## CNS disorders cure using CRISPR-Cas9
This technology seems promising in curing Central Nervous System diseases as well. The CRISPR-mediated deletion of a CGC repeat in FMR1 gene of stem cells reverses the transcriptionally repressed chromatin state of the gene and results in restoration of normal gene expression of FMR1 gene in the cells of the patients with Fragile X Syndrome. In patients with Huntington’s disease, the correction of a CAG repeat in the HTT gene in stem cells shows phenotypic reversals in the abnormalities observed in the patients suffering from Huntington’s disease. In spite of successful laboratory trials, the exploitation of CRISPR-Cas9 technology in neuroscience has not flourished enough yet in the biomedical research as genome editing and delivering machinery in the brain in vivo seems challenging.

# Challenges involved in CRISPR-Cas9 applications
Although the CRISPR-Cas9 technology provides enormous therapeutic potential, it also poses various challenges for its safe use in the field of gene therapy and clinical applications. Some of the challenges include off-target mutations which can impair the fitness or the functionality of edited cells or both or can generate potential oncogenic cell clones. In non-dividing cells like neurons, gene editing is difficult because editing a specific gene sequence relies on HDR (Homology Directed Repair) rather than NHEJ (Non-Homologous End Joining) and HDR is selectively expressed during mitosis. Additional challenges include the in vivo delivery of CRISPR-Cas9 system in genetic diseases and disorders which require the correction of cells in formed tissues in the patient’s body. This can be overcome by lentiviral vectors which has been widely and successfully used in different applications. Another issue is that a high frequency of antibodies and anti-Cas9 cytotoxic T-lymphocytes has been documented against SaCas9 and SpCas9 which are derived from Streptococcus aureus and Streptococcus pyogenes, microorganisms which are known to frequently infect humans. This issue can be resolved by using Cas9 derived from bacterial species that do not infect humans commonly.

# Ethical issues involved in use of CRISPR-Cas9 tool
For a technology which is so versatile and so enabling, it seems very necessary to take into account its societal and ethical implications for making targeted changes to the DNA of organisms. This is a profound thing that gives humans the power to control evolution of organisms and environment and potentially our own evolution in a much-targeted fashion. And so, a lot of discussion has been triggered around the world by this technology about its ethics. Very recently, this has led to the release of the document by the Nation Academy of Sciences entitled “Human Genome Editing: Science, Ethics, and Governance” which goes through all the implications of human genome editing, especially permanently editing human germline, which creates many concerns, and how it is a roadmap to show how the scientific community and global community can move ahead to ensure that there is occurrence of robust research and provides appropriate regulations for the use of a very powerful technological tool. With the advancements of technologies, the boundaries between a cure and eugenics applications are becoming very thin which calls for immediate need to promote general, worldwide-accepted protocols, which will require close interaction between the regulatory agencies, scientific communities and governments of different countries. To shed light on this matter a global moratorium on the use of genome editing technologies for human germline modification has recently been called for, to allow time to discuss the relevant scientific and ethical issues.

# Conclusion
The potential of CRISPR/Cas9 is immensely high, but researchers must proceed with utmost care and caution. New discoveries, data and protocols will most likely help to address the many fundamental problems involved, and CRISPR will lead to a new revolution in the field of biomedical sciences and molecular biology.

# References
1.	Gavin J. Knott and Jennifer A. Doudna. CRISPR-Cas guides the future of genetic engineering. Science. 2018 Aug 31; 361(6405): 866–869. doi: 10.1126/science.aat5011 
2.	Alexandre Loureiro and Gabriela Jorge da Silva. CRISPR-Cas: Converting A Bacterial Defence Mechanism into A State-of-the-Art Genetic Manipulation Tool. Antibiotics (Basel). 2019 Mar; 8(1): 18. doi: 10.3390/antibiotics8010018 
3.	Edyta Janik, Marcin Niemcewicz and Michal Bijak. Various Aspects of a Gene Editing System—CRISPR–Cas9. Int J Mol Sci. 2020 Dec; 21(24): 9604. doi: 10.3390/ijms21249604 
4.	Vo Van Giau, Hyon Lee and Seong Soo A An. Genome-editing applications of CRISPR–Cas9 to promote in vitro studies of Alzheimer’s disease. Clin Interv Aging. 2018; 13: 221–233. doi: 10.2147/CIA.S155145 
5.	Martin Jinek, Alexandra East and Jennifer Doudna. RNA-programmed genome editing in human cells. eLife. 2013; 2: e00471. doi: 10.7554/eLife.0047 
6.	Precilla S. Daisy, Kuduvalli S. Shreyas, and T. S. Anitha. Will CRISPR-Cas9 Have Cards to Play Against Cancer? An Update on its Applications. Mol Biotechnol. 2021 Jan 1 : 1–16. doi: 10.1007/s12033-020-00289-1 
7.	Maria Teresa Valenti, Michela Serena and Donato Zipeto. CRISPR/Cas system: An emerging technology in stem cell research. World J Stem Cells. 2019 Nov 26; 11(11): 937–956. doi: 10.4252/wjsc.v11.i11.937 
8.	Aino Vesikansa. Unraveling of Central Nervous System Disease Mechanisms Using CRISPR Genome Manipulation. J Cent Nerv Syst Dis. 2018; 10: 1179573518787469. doi: 10.1177/1179573518787469 
